---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 7.2.1
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  values:
    annotations:
      secret.reloader.stakater.com/reload: velero-s3-secret
    image:
      repository: velero/velero
      tag: v1.16.0
    configuration:
      extraEnvVars:
        TZ: "Europe/Paris"
      provider: aws
      backupStorageLocation:
        name: default
        bucket: velero-backups
        default: true
        config:
          region: eu-west-1
          s3ForcePathStyle: true
          s3Url: http://192.168.69.69:9000
      resticTimeout: 4h
    credentials:
      existingSecret: velero-s3-secret
    schedules:
      daily-backup:
        # At 6:00am in the morning every day
        schedule: "0 6 * * *"
        template:
          ttl: "168h"
      weekly-backup:
        # At the end of the week on a Sunday morning, at 6:00am
        schedule: "0 3 * * 0"
        template:
          ttl: "338h"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
        spec:
          - alert: VeleroDailyBackupPartialFailures
            annotations:
              message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partially failed backups.
            expr: |-
              velero_backup_partial_failure_total{schedule="velero-daily-backup"} / velero_backup_attempt_total{schedule="velero-daily-backup"} > 1
            for: 15m
            labels:
              severity: warning
          - alert: VeleroDailyBackupFailures
            annotations:
              message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} failed backups.
            expr: |-
              velero_backup_failure_total{schedule="velero-daily-backup"} / velero_backup_attempt_total{schedule="velero-daily-backup"} > 1
            for: 15m
            labels:
              severity: warning
    backupsEnabled: true
    snapshotsEnabled: false
    upgradeCRDs: false
    cleanUpCRDs: false
    # kubectl:
    #   image:
    #     repository: docker.io/bitnami/kubectl
    #     tag: 1.24
    deployNodeAgent: false
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.10.1@sha256:fdf710a65c6ead48b1018cda19360943abe17ca8c3e9ef5ab7be73a63b99a6d3
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
