---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: siyuan
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: siyuan-secret
    template:
      data:
        AUTH_CODE: "{{ .AUTH_CODE }}"
  dataFrom:
    - extract:
        key: docmost
