---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
spec:
  interval: 1h
  chart:
    spec:
      chart: snapshot-controller
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    controller:
      serviceMonitor:
        create: true
