---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafana_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
spec:
  external:
    url: https://chippermagpie793.grafana.net
    tenantNamespace: observability
    apiKey:
      name: grafana-cloud-credentials
      key: GRAFANA_CLOUD_GRAFANA_TOKEN
