---
apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: keda-prometheus-credentials
spec:
  secretTargetRef:
    - parameter: username
      name: grafana-cloud-credentials
      namespace: observability
      key: GRAFANA_CLOUD_PROMETHEUS_USER
    - parameter: password
      name: grafana-cloud-credentials
      namespace: observability
      key: GRAFANA_CLOUD_API_TOKEN
