---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  - ./kubelet-csr-approver/ks.yaml
  - ./spegel/ks.yaml
  - ./external-secrets/ks.yaml
  - ./local-path-provisioner/ks.yaml
  - ./intel-device-plugin-operator/ks.yaml
  - ./csi-driver-nfs/ks.yaml
