---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-cloud-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PROMETHEUS_ENDPOINT: 'https://{{ .GRAFANA_CLOUD_PROMETHEUS_USER }}:{{ .GRAFANA_CLOUD_API_TOKEN }}@{{ trimPrefix "https://" (trimSuffix "/push" .GRAFANA_CLOUD_PROMETHEUS_URL) }}'
  dataFrom:
    - extract:
        key: grafana-cloud
