---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-metrics
  interval: 1h
  values:
    fullnameOverride: vm
    victoria-metrics-operator:
      admissionWebhooks:
        policy: Ignore
      crds:
        cleanup:
          enabled: false
      operator:
        enable_converter_ownership: true
    grafana:
      enabled: false
    defaultDashboards:
      grafanaOperator:
        enabled: true
        spec:
          allowCrossNamespaceImport: true
    defaultDatasources:
      grafanaOperator:
        enabled: true
        spec:
          allowCrossNamespaceImport: true
    kube-state-metrics:
      enabled: false
    prometheus-node-exporter:
      enabled: false
    alertmanager:
      enabled: false
    vmalert:
      enabled: false
    kubeControllerManager:
      vmScrape:
        spec:
          endpoints:
            - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              port: http-metrics
              scheme: https
              tlsConfig:
                insecureSkipVerify: true
    kubeEtcd:
      service:
        selector:
          component: kube-apiserver
        port: 2381
        targetPort: 2381
      vmScrape:
        spec:
          endpoints:
            - scheme: http
    kubeScheduler:
      vmScrape:
        spec:
          endpoints:
            - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              port: http-metrics
              scheme: https
              tlsConfig:
                insecureSkipVerify: true
    vmagent:
      spec:
        scrapeInterval: 60s
        externalLabels:
          cluster: main
        extraArgs:
          promscrape.dropOriginalLabels: "true"
          promscrape.maxScrapeSize: 50MiB
          promscrape.streamParse: "true"
    vmauth:
      enabled: true
      spec:
        extraArgs:
          requestBufferSize: "65536"
        unauthorizedUserAccessSpec:
          url_map:
            - src_paths:
                - /api/v1/query.*
                - /api/v1/label/.*
              url_prefix: http://vmsingle-vm.observability.svc.cluster.local:8428
            - src_paths:
                - /select/logsql/.*
              url_prefix: http://victoria-logs.observability.svc.cluster.local:9428
    vmsingle:
      spec:
        retentionPeriod: 30d
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
          limits:
            memory: 2Gi
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          storageClassName: ceph-block
