---
# Areas
- { name: "area/bootstrap",             color: "0e8a16" }
- { name: "area/github",                color: "0e8a16" }
- { name: "area/kubernetes",            color: "0e8a16" }
- { name: "area/minecraft",             color: "0e8b16" }
# Renovate Types
- { name: "renovate/container",         color: "027fa0" }
- { name: "renovate/github-action",     color: "027fa0" }
- { name: "renovate/grafana-dashboard", color: "027fa0" }
- { name: "renovate/github-release",    color: "027fa0" }
- { name: "renovate/helm",              color: "027fa0" }
- { name: "renovate/pip",               color: "027fa0" }
# Semantic Type
- { name: "type/patch",                 color: "ffec19" }
- { name: "type/minor",                 color: "ff9800" }
- { name: "type/major",                 color: "f14183" }
- { name: "type/break",                 color: "f6412d" }
- { name: "type/digest",                color: "ffeC19" }
# Uncategorized
- { name: "do not merge",                       color: "ee0701" }
# General
- { name: "bug",                        color: "a4ffae" }
- { name: "deploy",                     color: "1f6feb" }
- { name: "improvement",                color: "ff9800" }
- { name: "broken",                     color: "ee0701" }
# Status
- { name: "status/priority",            color: "519fd0" }
