---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: thanos
      version: 10.5.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: public.ecr.aws
      repository: bitnami/thanos
    query:
      enabled: true
      replicaLabels:
        - replica
      dnsDiscovery:
        sidecarsService: prometheus-thanos-discovery
        sidecarsNamespace: monitoring
      ingress:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - hosts: "thanos.${SECRET_DOMAIN}"
            paths:
              - "/"
        tls:
          - secretName: thanos
            hosts:
              - "thanos.${SECRET_DOMAIN}"
    existingObjstoreSecret: thanos-objstore
    queryFrontend:
      enabled: false
    bucketweb:
      enabled: true
    compactor:
      enabled: true
      persistence:
        enabled: false
    storegateway:
      enabled: true
      persistence:
        storageClass: "longhorn"
        accessModes:
          - ReadWriteOnce
        enabled: true
        size: 3Gi
    ruler:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
