---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: seerr-secret
    template:
      data:
        # Postgres Init
        INIT_POSTGRES_DBNAME: seerr
        INIT_POSTGRES_HOST: db.internal
        INIT_POSTGRES_USER: "{{ .SEERR_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .SEERR_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Seerr DB config
        DB_TYPE: postgres
        DB_HOST: db.internal
        DB_PORT: "5432"
        DB_USER: "{{ .SEERR_POSTGRES_USER }}"
        DB_PASS: "{{ .SEERR_POSTGRES_PASS }}"
        DB_NAME: seerr
  dataFrom:
    - extract:
        key: seerr
    - extract:
        key: cloudnative-pg
