---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tailscale-gateway
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      tailscale-gateway:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/tailscale/tailscale
              tag: v1.68.1@sha256:a0d1a9ed2abfacf905c0e3423aea00181064162e548f875f422a03924b9cc5c4
            env:
              TZ: ${TIMEZONE}
              NO_AUTOUPDATE: true
              PORT: &port ${TAILNET_PUBLIC_PORT}
              TS_EXTRA_ARGS: --advertise-exit-node --advertise-tags=tag:server
              TS_ROUTES: "192.168.69.0/24,192.168.88.0/24"
              TS_STATE_DIR: &path /tmp
              TS_TAILSCALED_EXTRA_ARGS: --debug=0.0.0.0:2000
              TS_USERSPACE: true
              # TS_EXTRA_ARGS: "--snat-subnet-routes=false --advertise-exit-node"
              # TS_ACCEPT_DNS: "false"
            envFrom:
              - secretRef:
                  name: tailscale-secret
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      # topologySpreadConstraints:
      #   - maxSkew: 1
      #     topologyKey: kubernetes.io/hostname
      #     whenUnsatisfiable: DoNotSchedule
      #     labelSelector:
      #       matchLabels:
      #         app.kubernetes.io/name: *app
    persistence:
      cache:
        type: emptyDir
        globalMounts:
          - path: /.cache
      tmp:
        type: emptyDir
        globalMounts:
          - path: *path
    service:
      app:
        controller: *app
        nameOverride: *app
        ports:
          http:
            port: 2000
      tailnet:
        controller: *app
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${TAILSCALE_LB_IP}
        ports:
          tailnet:
            port: *port
            protocol: UDP
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http
            scheme: http
            path: /debug/metrics
            interval: 1m
            scrapeTimeout: 10s
