---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./external-secrets.yaml
  - ./rook-ceph.yaml
  - ./piraeus.yaml
  - ./democratic-csi.yaml
  - ./hajimari.yaml
  - ./backube.yaml
  - ./grafana.yaml
  - ./nvidia.yaml
