---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kaizoku
  namespace: media
spec:
  interval: 15m
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/oae/kaizoku
      tag: v1.6.1
    env:
      TZ: "${TZ}"
      DATABASE_URL: "postgresql://kaizoku:${SECRET_KAIZOKU_DB_PASSWORD}@postgresql.database.svc.cluster.local:5432/kaizoku"
      KAIZOKU_PORT: 3000
      REDIS_HOST: redis-master.database.svc.cluster.local
      REDIS_PORT: 6379
      PUID: 1000
      PGID: 1000
    service:
      main:
        ports:
          http:
            port: &port 3000
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: "simple-icons:kaios"
          hajimari.io/group: "media"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 2Gi
        storageClass: longhorn

    persistence:
      nfs-nas-media:
        enabled: true
        existingClaim: media-nfs-share-pvc
        mountPath: /data
        readOnly: false

    # resources:
    #   requests:
    #     cpu: 15m
    #     memory: 350M
    #   limits:
    #     memory: 600M
