---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app botkube
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: ./kubernetes/apps/monitoring/botkube/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  # disable wait as for some reason it doesn't work
  wait: false
  dependsOn:
    - name: kube-prometheus-stack
