---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-cloud-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PROMETHEUS_URL: "http://metrics.internal"
        LOKI_URL: "http://logs.internal"
        GRAFANA_URL: "https://grafana.internal"
        GRAFANA_API_TOKEN: "{{ .GRAFANA_API_TOKEN }}"
        KROMGO_PROMETHEUS_URL: "http://metrics.internal"
  dataFrom:
    - extract:
        key: observability-vm
