---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-cloud-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GRAFANA_CLOUD_PROMETHEUS_URL: '{{ .GRAFANA_CLOUD_PROMETHEUS_URL }}'
        GRAFANA_CLOUD_PROMETHEUS_USER: '{{ .GRAFANA_CLOUD_PROMETHEUS_USER }}'
        GRAFANA_CLOUD_LOKI_URL: '{{ .GRAFANA_CLOUD_LOKI_URL }}'
        GRAFANA_CLOUD_LOKI_USER: '{{ .GRAFANA_CLOUD_LOKI_USER }}'
        GRAFANA_CLOUD_API_TOKEN: '{{ .GRAFANA_CLOUD_API_TOKEN }}'
        KROMGO_PROMETHEUS_URL: 'https://{{ .GRAFANA_CLOUD_PROMETHEUS_USER }}:{{ .GRAFANA_CLOUD_API_TOKEN }}@{{ trimPrefix "https://" .GRAFANA_CLOUD_PROMETHEUS_URL }}'
  dataFrom:
    - extract:
        key: grafana-cloud
