---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  interval: 15m
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  chart:
    spec:
      version: 1.5.1
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: lscr.io/linuxserver/lidarr
      tag: 1.0.2.2592-ls101
    env:
      TZ: "${TIMEZONE}"
      LIDARR__INSTANCE_NAME: Lidarr
      # LIDARR__PORT: &port 80
      LIDARR__LOG_LEVEL: info
      PUID: 0
      PGID: 0
    envFrom:
      - secretRef:
          name: lidarr-secret
    service:
      main:
        ports:
          http:
            port: 8686
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: "music-box"
          hajimari.io/group: "media"
        hosts:
          - host: &host-release "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host-release
    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    persistence:
      config:
        enabled: true
        existingClaim: lidarr-config-v1
      nfs-nas-media:
        enabled: true
        existingClaim: media-nfs-share-pvc
        mountPath: /media
        readOnly: false
      # backup:
      #   enabled: true
      #   type: nfs
      #   server: "expanse.${SECRET_PRIVATE_DOMAIN}"
      #   path: /tycho/Apps/External/Backups/lidarr
      #   mountPath: /config/Backups
      #   readOnly: false
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2000Mi
