---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: &name gatus
  annotations:
    policies.kyverno.io/title: Generate gatus endpoints
    policies.kyverno.io/category: Monitoring
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: HTTPRoute
    policies.kyverno.io/description: >-
      This policy will automatically generate gatus endpoints for
      all HTTPRoutes with parentRefs pointing to the external gateway.
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  generateExisting: true
  rules:
    - name: *name
      match:
        any:
          - resources:
              kinds:
                - HTTPRoute
      exclude:
        any:
          - resources:
              kinds:
                - HTTPRoute
              annotations:
                gatus.io/enabled: "false"
      preconditions:
        all:
          - key: "{{ request.object.spec.parentRefs[0].name }}"
            operator: Equals
            value: external
      context:
        - name: GATUS_HOST
          variable:
            value: '{{ request.object.metadata.annotations."gatus.io/host" || request.object.spec.hostnames[0] }}'
            jmesPath: "to_string(@)"
        - name: GATUS_NAME
          variable:
            value: '{{ request.object.metadata.annotations."gatus.io/name" || request.object.metadata.name }}'
            jmesPath: "to_string(@)"
        - name: GATUS_PATH
          variable:
            value: '{{ request.object.metadata.annotations."gatus.io/path" || request.object.spec.rules[0].matches[0].path.value || `/` }}'
            jmesPath: "to_string(@)"
        - name: GATUS_STATUS_CODE
          variable:
            value: '{{ request.object.metadata.annotations."gatus.io/status-code" || `200` }}'
            jmesPath: "to_string(@)"
      generate:
        apiVersion: v1
        kind: ConfigMap
        name: "{{ request.object.metadata.name }}-gatus-ep"
        namespace: "{{ request.object.metadata.namespace }}"
        synchronize: true
        data:
          kind: ConfigMap
          metadata:
            labels:
              gatus.io/enabled: "true"
          data:
            config.yaml: |-
              ---
              endpoints:
                - name: {{ GATUS_NAME }}
                  url: https://{{ GATUS_HOST }}{{ GATUS_PATH }}
                  interval: 1m
                  client:
                    dns-resolver: tcp://1.1.1.1:53
                  conditions:
                    - "[STATUS] == {{ GATUS_STATUS_CODE }}"
                  alerts:
                    - type: pushover
