---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glance
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: glance-config-secret
    template:
      data:
        glance.yml: |
          theme:
            background-color: 0 0 6
            primary-color: 157 47 65
            contrast-multiplier: 1.2

            presets:
              default-dark:
                background-color: 0 0 16
                primary-color: 43 59 81
                positive-color: 61 66 44
                negative-color: 6 96 59

              default-light:
                light: true
                background-color: 0 0 95
                primary-color: 0 0 10
                negative-color: 0 90 50

          server:
            port: 80
            proxied: true

          auth:
            secret-key: {{ .GLANCE_SECRET_KEY }}
            users:
              admin:
                password: {{ .GLANCE_ADMIN_PASSWORD }}

          pages:
            - name: Home
              columns:
                - size: small
                  widgets:
                    - type: custom-api
                      title: Unifi
                      cache: 1m
                      allow-insecure: true
                      url: https://192.168.69.1/proxy/network/api/stat/sites
                      headers:
                        X-API-KEY: {{ .UNIFI_API_KEY }}
                        Accept: application/json
                      template: |
                        <div class="flex flex-col gap-3 text-center">
                          <div class="glance-theme-text">{{ `{{` }} .Status {{ `}}` }}</div>
                          <div class="flex gap-2 justify-center">
                            {{ `{{-` }} range .Data {{ `}}` }}
                            <div class="flex flex-col p-3 rounded border glance-theme-border">
                              <div class="glance-theme-text-muted text-xs">{{ `{{` }} .Name {{ `}}` }}</div>
                              <div class="text-lg">{{ `{{` }} .NumUser {{ `}}` }}</div>
                            </div>
                            {{ `{{-` }} end {{ `}}` }}
                          </div>
                        </div>
                    - type: extension
                      url: http://k8s-extension:8080/extension/nodes
                      allow-potentially-dangerous-html: true
                      cache: 1s



                - size: full
                  widgets:
                    - type: search
                      search-engine: kagi

                    - type: bookmarks
                      groups:
                        - title: Entertainment
                          color: 10 70 50
                          links:
                            - title: YouTube
                              url: https://youtube.com
                            - title: Netflix
                              url: https://netflix.com

                        - title: DevOps
                          color: 200 50 50
                          links:
                            - title: Artifacthub
                              url: https://artifacthub.io
                            - title: k8s-at-home-search
                              url: https://nanne.dev/k8s-at-home-search/
                            - title: Git-cleaner
                              url: https://gitcleaner.com
                            - title: K8S Exam simulator
                              url: https://killer.sh
                            - title: Github-download-folder
                              url: https://download-directory.github.io/

                        - title: Fun
                          color: 200 50 50
                          links:
                            - title: Archive
                              url: https://archive.org
                            - title: Wallpapers
                              url: https://wallhaven.cc
                            - title: Diving-sites
                              url: https://divesites.com

                        - title: Hacking
                          color: 200 50 50
                          links:
                            - title: Shodan
                              url: https://shodan.io
                            - title: Intelx
                              url: https://intelx.io
                            - title: Greynoise
                              url: https://greynoise.io
                            - title: GrayHatWarFare
                              url: https://grayhatwarfare.com
                            - title: GPP Tools
                              url: https://gpptools.com
                            - title: BGP View
                              url: https://bgp.he.net
                            - title: ViewDNS
                              url: https://viewdns.info
                            - title: DNSChecker
                              url: https://dnschecker.org
                    - type: extension
                      url: http://k8s-extension:8080/extension/apps
                      allow-potentially-dangerous-html: true
                      cache: 1s



                    - type: rss
                      limit: 10
                      collapse-after: 3
                      cache: 12h
                      feeds:
                        - url: https://selfh.st/rss/
                          title: selfh.st
                          limit: 5
                        - url: https://ciechanow.ski/atom.xml
                        - url: https://www.joshwcomeau.com/rss.xml
                          title: Josh Comeau
                        - url: https://samwho.dev/rss.xml
                        - url: https://blog.cloudflare.com/rss
                          title: Cloudflare Blog

                - size: small
                  widgets:
                    - type: bookmarks
                      groups:
                        - title: Links
                          color: 200 50 50
                          links:
                            - title: Unifi
                              url: https://192.168.69.1
                            - title: Router
                              url: https://192.168.1.1
                            - title: Home-Ops
                              url: https://github.com/akira6592/home-ops

                    - type: weather
                      location: Brno, Czechia
                      units: metric
                      hour-format: 24h

            - name: news
              head-widgets:
                - type: markets
                  hide-header: true
                  markets:
                    - symbol: SPY
                      name: S&P 500
                    - symbol: TSLA
                      name: Tesla
                      chart-link: https://www.tradingview.com/chart/?symbol=INDEX:BTCUSD
                    - symbol: DAX
                      name: DAX
                    - symbol: ^N225
                      name: Nikkei 225

              columns:
                - size: full
                  widgets:
                    - type: group
                      widgets:
                        - type: hacker-news
                          sort-by: best
                        - type: lobsters
                          sort-by: hot
                        - type: reddit
                          subreddit: selfhosted
                          show-thumbnails: false
                          sort-by: hot
                          comments-url-template: https://old.reddit.com/{url}
                        - type: reddit
                          subreddit: kubernetes
                          show-thumbnails: false
                          sort-by: hot
                          comments-url-template: https://old.reddit.com/{url}
                        - type: reddit
                          subreddit: europe
                          show-thumbnails: false
                          sort-by: hot
                          comments-url-template: https://old.reddit.com/{url}
                        - type: reddit
                          subreddit: plex
                          show-thumbnails: false
                          sort-by: hot
                          comments-url-template: https://old.reddit.com/{url}
                        - type: reddit
                          subreddit: NonCredibleDefense
                          show-thumbnails: false
                          sort-by: hot
                          comments-url-template: https://old.reddit.com/{url}
                        - type: reddit
                          subreddit: midjourney
                          show-thumbnails: false
                          sort-by: hot
                          comments-url-template: https://old.reddit.com/{url}

                - size: small
                  widgets:
                    - type: releases
                      cache: 1d
                      repositories:
                        - kubernetes/kubernetes
                        - prometheus/prometheus
                        - grafana/grafana
                        - kubernetes-sigs/external-dns
                        - argoproj/argo-cd
  dataFrom:
    - extract:
        key: glance
    - extract:
        key: unifi
