---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app glance
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      glance:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          glance:
            image:
              repository: glanceapp/glance
              tag: v0.8.4@sha256:6df86a7e8868d1eda21f35205134b1962c422957e42a0c44d4717c8e8f741b1a
            env:
              TZ: Europe/Paris
            envFrom:
              - secretRef:
                  name: recyclarr-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 64Mi
              limits:
                memory: 96Mi
          k8s-extension:
            image:
              repository: ghcr.io/lukasdietrich/glance-k8s/glance-k8s
              tag: v0.4.0@sha256:8754b03b380cc9de59be4b144ab7adfaa0d07920048b59d08040968c28b25f09
            env:
              TZ: Europe/Paris
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources: {}
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: 8080
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: 8080
        serviceAccount:
          identifier: *app
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
    service:
      glance:
        controller: glance
        ports:
          http:
            port: &port 80
      k8s-extension:
        controller: glance
        ports:
          http:
            port: 8080
    route:
      glance:
        hostnames:
          - glance.juno.moe
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      config-file:
        type: configMap
        name: glance-configmap
        globalMounts:
          - path: /app/config/glance.yml
            subPath: glance.yml
            readOnly: true
    serviceAccount:
      glance:
        enabled: true
    rbac:
      roles:
        list:
          type: ClusterRole
          forceRename: *app
          rules:
            - apiGroups: ["", "metrics.k8s.io"]
              resources: ["nodes"]
              verbs: ["list"]
            - apiGroups: [""]
              resources: ["services"]
              verbs: ["list"]
            - apiGroups: ["networking.k8s.io"] # networking.k8s.io/v1
              resources: ["ingresses", "ingressclasses"]
              verbs: ["list"]
            - apiGroups: ["apps"]
              resources: ["deployments", "statefulsets", "daemonsets"]
              verbs: ["list"]
      bindings:
        list:
          type: ClusterRoleBinding
          forceRename: *app
          roleRef:
            kind: ClusterRole
            name: *app
          subjects:
            - kind: ServiceAccount
              name: *app
              namespace: "{{ .Release.Namespace }}"
