---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: kubernetes
spec:
  provider:
    kubernetes:
      remoteNamespace: rook-ceph
      auth:
        serviceAccount:
          name: external-secrets
          namespace: kube-system
