---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: karakeep
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: karakeep-secret
    template:
      data:
        NEXTAUTH_SECRET: "{{ .ENCRYPTION_KEY }}"
        MEILI_MASTER_KEY: "{{ .MEILISEARCH_MASTER_KEY }}"
        # AI
        OPENAI_BASE_URL: "{{ .OPENAI_BASE_URL }}"
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        # OIDC
        OAUTH_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OAUTH_PROVIDER_NAME: Authentik
        OAUTH_WELLKNOWN_URL: https://sso.juno.moe/application/o/karakeep/.well-known/openid-configuration
        OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: "true"
  dataFrom:
    - extract:
        key: karakeep
