---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: karakeep
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: karakeep-secret
    template:
      data:
        NEXTAUTH_SECRET: "{{ .ENCRYPTION_KEY }}"
        MEILI_MASTER_KEY: "{{ .MEILISEARCH_MASTER_KEY }}"
        OPENAI_BASE_URL: "{{ .OPENAI_BASE_URL }}"
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
  dataFrom:
    - extract:
        key: karakeep
      # rewrite:
      #   - regexp:
      #       source: "[^a-zA-Z0-9 -]"
      #       target: "_"