---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
spec:
  provider:
    onepasswordSDK:
      vault: home-ops
      auth:
        serviceAccountSecretRef:
          name: onepassword-token
          key: token
          namespace: kube-system
