---
# yaml-language-server: $schema=https://raw.githubusercontent.com/axeII/crds/main/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
  namespace: kube-system
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.kube-system.svc.cluster.local
      vaults:
        home-ops: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-secret
            key: token
            namespace: kube-system
