# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-secret
  namespace: kube-system
stringData:
  1password-credentials.json:
    verifier:
      salt: ENC[AES256_GCM,data:ZQsxGeyfp0fiwbcAUMlyzOTWUUxluA==,iv:CEQ/X3idrw1VQAiv/xt5AhqePy4/Nx4fYtMElgrq1qE=,tag:XrJ6X9y9qi/GaP0kyDhtGQ==,type:str]
      localHash: ENC[AES256_GCM,data:YoVHoPnghcDja/m52m9rEl8PVWCfMwupZHf0gLrsqB4dmMz0IbHvjp0CrA==,iv:7l8qwfXlWsmj3AcOMcgfgYZsVhl0E+ecSxT+VqRJAqc=,tag:ESz+EM7lhHHdoYf0fHHkbQ==,type:str]
    encCredentials:
      kid: ENC[AES256_GCM,data:m/3Jy9A+yTOkuq0aI6wKYEE=,iv:xtBQkg6A3Mb9IyRboPmurQYo8Nlp2MtX3nvU7cD+U/c=,tag:H2dve7yewmRCLWtt7/20jg==,type:str]
      enc: ENC[AES256_GCM,data:+S037Qlcww==,iv:WB0ju2WSmwSFqG9N+gREA+3SEyrsQholAdHCDll9+yU=,tag:1J4P4YHs/qPNBrSH9urZZQ==,type:str]
      cty: ENC[AES256_GCM,data:BK4r+MWGZCj/24o=,iv:ri1H1foN92wxANZg/iG1+wbgLoVoICYSY1BOvUbD0xk=,tag:yFAfcF7cWUIVWYcMZbi+hQ==,type:str]
      iv: ENC[AES256_GCM,data:+FfWUSK3hKubNI/7YCdF2w==,iv:a6yAVgMun8MT7PUZjUkkknqx0FnZEO1UPe1E6Uvgggc=,tag:dnhstWOD1mwwWukvHsQVGA==,type:str]
      data: ENC[AES256_GCM,data:XHvIHk8JNoSGb83Wj3EfJ1h+Rq537/KtaCcJNNljc0czEyzRNKGGrV1Jrn0ALUwa4SFvy40ATNaQVyjt3ZtD+a+u604iQXif34IhCzlhQ7WPOPCpRXqDy9LI0P+Sl/fICf06M+t9nVfp5bi+cCzMPIzZdeSmKt/cT2Skbe4xlnwLVDdwgfyeLoBespHlL/spu0GRSRRbI6qoiPBivvHq4GKzUWnslSmiUeb5mlp3Lt8suttP6558lqYMt3xeMTLxODR4Ab6V0QzlrWu0pEEKyOvMGpxngvnGrocgMP+n/04TxssiONrBdLangQ7KysJUqZrrc4szCfFvCXk84jttIu75ki2v4cTdp64J0XWHyO0JbHGWAIo1sFcb8q81o+MpLXRsb8gWOIp7IcggOT8eFZ58v8o9IztoZcWei2aSnUX+6b0kwwrDXM82eaQDtEKx2cORzSvo19KgSI4U27q4tbND7enbW0mGciOLo8u8bw6/6Az0O9IBqLe/JvnpfTfpK/MzguitfUOpkQAjoywMpZ3CS+Nk4bhxcfDyEjBEEB5rJIj+AiPtq4BQ2Q/7G/fOtLWrUElVFNOGcFteiYv9HnqFGeJqHSksMltG5bdJ0XesTo9a8wbWVbVZmFPTD4pp0QrV4VrfA+843jfatLtaeViFCehQpM0xru1Pb/4PYBJTOAZJ59NFhjSvxMjT86smChO39pFY9iSEJw1HPVpgSLPA+qHfDQioD8/P/T6YqzSqmdbFGs9A2zgO1WJERiuiEY+4IZFo6dr1YCtah/CUUF80T2+r/WM29cW1AsBlrPFekHo9Nl78GClhfpOfZO69cmmPRdCloa0a9bgj2mGx02ph,iv:1Oo5vaWHUAKIaelTYL5VQOqQJjhiVQHNkpVXtIu3TbI=,tag:Hnndi3R6O9RrEo8djY73Dg==,type:str]
    version: ENC[AES256_GCM,data:tg==,iv:4AchPcQ4paGb/nV4rUOqDyZ+/QFYJpsyFk85tLdk5V8=,tag:N8CjYAocUbdp1b1npnU0Gw==,type:str]
    deviceUuid: ENC[AES256_GCM,data:VqOLoFSHz4qQB2zsSJ1YtoWabi79GxHGVrE=,iv:Q7ceWetIPuUlZCuMcd+7lBoD/y5KVG+Ck2vNoHQ4n2w=,tag:nDUfqOy62hVhtDFlEBiMvA==,type:str]
    uniqueKey:
      alg: ENC[AES256_GCM,data:ARPzJYSU5Q==,iv:h+1tZlovXfdVmBafu6OZATURMFqyhrCJW/L5rsNT0Wk=,tag:B4SJCQeyHldZcsKvBvTHzw==,type:str]
      ext: ENC[AES256_GCM,data:ezLRzw==,iv:G5leUZyai0zSdWZiJira3xp+p9VvTTd+3MW2dObMuB4=,tag:rz26m3sLuvATZqWjU3+qPw==,type:bool]
      k: ENC[AES256_GCM,data:EAmYQ9HGQaAn8VVxwO5gQGN4sm4x4NThX9GZHi/Hnoxd4m5s4S2ROiIncw==,iv:yKr7qKGD1Jfst3QmXuH4wFM4fJxj9M//TOXPE+KowEU=,tag:Mfa8HXJSvJTXqNpEuNeq2A==,type:str]
      key_ops:
        - ENC[AES256_GCM,data:JzcBw3OnVg==,iv:q++bfwSi1S5399o5jGZxSktK8obWk7GJt58mlqXQ2x0=,tag:AeSCqgeU3OacEQNkHOLgPw==,type:str]
        - ENC[AES256_GCM,data:m+PIJuntPQ==,iv:h1h9c3D3pfzj4phZWlDoMPjMHdU14He6DzO5T8YSCXQ=,tag:nrGk9+9QczqIu6sAjudVog==,type:str]
      kty: ENC[AES256_GCM,data:Xu+h,iv:qG57KIyY6WiZoLxwO0+kEAg34kFoc6N0qjkV9RXIaas=,tag:l3jsqhJ5DvhVAVyrcZRfew==,type:str]
      kid: ENC[AES256_GCM,data:k/+b/dCCrjcqbzQvANIh0NpaSmYkm31LL44=,iv:jnwjcWemB+mtTKzXF9R2YGhyvlad7Gl1XFQi0Etz5TM=,tag:uibjJUUHir/wrGBTwsQ56w==,type:str]
  token: ENC[AES256_GCM,data:qAI2cLkMemADReXHVq7EUyfUpuMTJJbZZxS+4xs41bSKMFAskkmMwjWgOVnLRgauCaKc/PYc8Vp7rz4CT2odQMJAlskHTIUOwuQ2jmPHmStNkg+epRnx7inpxczLGaBst5ddWws0JDQtP6tsab/mZgNUZ4cHgKTMBdW+C12RO9BOZIpsxpjFydJa647iOHU5qKh2sEiyfQNF7z/3fJOwGdfKBTFJMIyErdNdrm0q2h7+JePErKAs0QPb6Q+LoBoDP/juYP+quzNYXUX3xAv1Tx/ur+VQ0XYB8NOJfS/4AFiY0apQ4e/Vf2Ux7bvOwYeVFsKcvbO87s1GxKu34tndnbEAuThLEmysNbeIcXK4MI83CwUBqryiCui9BGZcztn9FLaHlYN3dBiDrPJZefbD02dRVEURrnR6bktCHrmMAQyVS6MekmNSFmCDqIyz30S0GzSIRBH4lXOLZiIFvZKXQrDAXAyfkviMNOfk2PviMhG/YJApq2Yr4oZ9gnUeKrtbJ8oXs6hGtAcfqFM09UcSVVu5p0R25V1c/ox87O5NQAVCcwpzwJ6vmdVivUzBo7jikwk28mHyvGnzb+p7KTaUF0Bi4kkIp9LjHa0nPPjp0cqIfTzbUMD3W4xVwMJENO/uLKhhxNDkB5V/m1ecjI0B+8V8AhAHtPFWK0QsJJ054vNZs3MwOBgKAiYjc4XtIGJA46eo+ZiTl9ZLQ5+4KGGCMa/nbLkUCjsAitluOidoPiaz2NYWGoITjmsb8ctQrYV/cc12nRM3diy9aGmj1Cex4cFmNrQNUGIaHV+lHxS+waqhPQvNef0D/uNZ7nBcFmzkbef1Y6OVOBg51O7p11TDVUSU,iv:As03ue3YQPEAD5lXWvBJvbSZj9WIwEqWTu/8YQ/imVc=,tag:UhZWAnhViRfqEW5g9e2VcQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSUNteTRmQlV6SE5nZ3Q2
        bnpySkNPQzNubjd4REsxdlZiUUtJMHBsSFVZCkJZZ3g5YkowNFErT3JBTjBBM0RE
        Lyt4TjhOcGZib01OTnd1VVprTkZ5bnMKLS0tIHc3TzZGQm9yaTV1cm1ZTVNvMjVm
        VFRZTTRndloydmtGemE2TWp3bVpzcVUKcNDjXGniuSoHfKAh3w038U+2IKk9g0LG
        VJXpdo+jgKA1qUw2uPsTEqD/iYk+5VP1C7ZhM3ANB5shw7WtO30Ifw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ryhy9dduzk5hyn33lnm7swtg72r7luklfv397s3wmhqav099w95s3cu3rh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-18T19:57:04Z"
  mac: ENC[AES256_GCM,data:OOaPlnfnx/jcUwNBrNUV/bjcGEu9J2bfvqxvEQ+CHXZXJnHV9CvDYq7qYqqUkRMmwG39HlqUOsbbsBXVZP5kSV7ejRslkAxEOww9+GYy5xYpTUv8+Wqi6w298YLyZlaDE8j0GreXwQvzzW5AAj7M9lfBQjdDQJYIoOAF5a3MPsA=,iv:FfIMpLcZRs91jiN2X8xtWr3RQnk5zlfW+dENA12OFCU=,tag:iKVl6kecTU1XY9Rr61YANg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
