# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-secret
  namespace: kube-system
stringData:
  1password-credentials.json:
    verifier:
      salt: ENC[AES256_GCM,data:TViVLT6hWfML92fjmCav+ckCxBjfFA==,iv:BDn9NaZkc7r9pmQtsCOHlbn66uHCD3cp9jSTGlDNuAQ=,tag:ZWtDW00PWSUgIUDnmzycAA==,type:str]
      localHash: ENC[AES256_GCM,data:A71Y3fw14gOmp9E7BjoGg8hMk6g/F5lPjt1Mrfj0cE/K1R4jAhcQqq0q8Q==,iv:jfVpRW7vz2Kt0CCaxaM+4cg22a2xcO//jO70PveJ0Hw=,tag:AOVwRPNMfbyjusolfgfj1A==,type:str]
    encCredentials:
      kid: ENC[AES256_GCM,data:g7we150oCD5nwHjZiuMBVUo=,iv:LwCe9oMY+VTSJnYwbk/eQfVwkW3X1ukmOSOiuSmhltc=,tag:C2GW5D3W2NLgMdU5L9g5mg==,type:str]
      enc: ENC[AES256_GCM,data:E7YkBzuswQ==,iv:Jl3GuPdVe8Wgqw0o1SMYu/p9WBzT1YD2376QyI92kEI=,tag:yt/wVYUOchSjmbygVTHXxQ==,type:str]
      cty: ENC[AES256_GCM,data:UPMO9uQjhSFQ2jc=,iv:U/EnXHJf2q1hh6gwNSZCnxDl+1YiHc6sMSKWYMsNVnY=,tag:6glMHPRWfX9ZRMm/9IHtGg==,type:str]
      iv: ENC[AES256_GCM,data:JB/m6yvE+UCjiz9fihh4oQ==,iv:nJI2oh9D1Xxkk0OKVbIqCbi8HggHR1cGBTXNyIpj6mo=,tag:vhvQ4N42j9LNDtxFLTXymg==,type:str]
      data: ENC[AES256_GCM,data:2zmahlghQGAAoGpHwTiDbOsZ9UXH7iBHXqWTApXapWi9nhZDSfrsKJweC4NGQp4KodU6AKm5ZlTJz7STw3aydIfzUbu887N2I/wKfBE/WWxNnkwD+FadxTEwfhWTe+IuTDqkYgdlFHLXwhrxVGpbATyUH1Eh+wYi7RqdUjW5Nbs1IfYDovOofr0NiigM4ZIOuWyEPTLQmn8/h5tOhqlOevTSXtX+DKuFWhmSLDmzXIUAjhgAgyIBcFBMYbA4qLG7Ak1TUgJ6AppIfPGtoFm9cKhpBbY9UTXwYLk4zvOq35MUbtCgtaf1l23Xebuelr+cIbMpGKwXrnmPOwIMGqvLjOMA8f92VhiW8O55TgwLId2p+/sszVix/6rB6/2vBYetQ2vpLERPuuM9jOOlhj5hYv7mdk+RZgBmRc6BT79UPQaq9ZCQFayOJMT/OVkvJPz4Qpg+5GmP7uTwfrRkp9X7muALVge26S7BGHaHRcXLrt23xZ+qkezJXz4vTrxO0cEgoHn39Tvn3FFPxOGluvb2CTRxznj4ODzj1lIBC2SplS2S4JIn5SVVTYR9L8mQBquJ2ePlSPoiqySQPGA0HKkuL1rU9s9uuM7eI+NwUQKzpcbSRNS1yL0f8GKPFnGUhv/stwEDOMjtA4y4EOwRDKSvWlihLS5nfjwO+fSuRsJXvNlY7BQNhytU5Cc35IUvuwOz+gRoAxILfk2X0MepVKKR8L0bUX5dabGJpkQyOylJcmLFwYprDKukoERJfLFN0y9Z5PalFqTA/d+NOUqZKhBaWgPlqhuL8JQRey/nTI8hnpoCVpQIMpQnYC2F6HOVqCQ2HWXsroJieyiwKEhKtjZJ+pan,iv:hvKONvjLRaIhd2mQDpBqQW67w9rYToC4802qiEZuDMI=,tag:9+sSPTmW5okOTWy5h5QQKg==,type:str]
    version: ENC[AES256_GCM,data:KA==,iv:rr34Uk7kmTnJhT4ZxpYq2ABthayuCKQAz/zZrGDJJSs=,tag:+SwYAmahCobIDwGP0Lkqtw==,type:str]
    deviceUuid: ENC[AES256_GCM,data:QTYQ5YiDA98op2aY0y6PibNOxZyAOwPxwDI=,iv:7ezvPNPxJmSBsRN+ctN2qg63j1LK2sZeL/eOmVmU2vU=,tag:QrHhCzwvyizpO3Pn1vsD3A==,type:str]
    uniqueKey:
      alg: ENC[AES256_GCM,data:FAPRvEM2Kg==,iv:w7FejzQN6fIWEcsCfrwPOY63wRt13EgVXxPpaQsx7LU=,tag:DkZCv7uVO+q0p9nbwEZRig==,type:str]
      ext: ENC[AES256_GCM,data:4or+1A==,iv:nKamBP10GbBSI2vPv1o59xaQg+yZe2E10fP6ZWUKQ3Q=,tag:BHkoo+FM/jqCGGScNs+aOQ==,type:bool]
      k: ENC[AES256_GCM,data:Ykey0puLosnB0jUp85MPWaw4jcMVqYN4yPA2ia9N+isY1pXWmav6tM8x4w==,iv:elNhXNjnY3yMsSDFX2BoapTMGR0tyHf4EkNMtgcRx0o=,tag:0P7eWiDtRqdIsGmoHXyXzA==,type:str]
      key_ops:
        - ENC[AES256_GCM,data:qdziD3wAxQ==,iv:IzHGjK+xhg+8VB6RYH2QboVlbWn2015WiUCXb4FNvAM=,tag:hBYq5bzmfoynJtx1iXSe4A==,type:str]
        - ENC[AES256_GCM,data:6/VPyJHf8w==,iv:1EkiYLlFVsAuxAwmVJRTM7JnDrMUp4c3FeX0CmzWsUg=,tag:DpzAVQmhHXY6rWJEkNmgmA==,type:str]
      kty: ENC[AES256_GCM,data:5iMR,iv:SHKZ9zwwn+2eesDzXn7emNWhoRhW44IsQgrs6SmXPyQ=,tag:tFpxW0GxYS1oyII47HYD+Q==,type:str]
      kid: ENC[AES256_GCM,data:7zxczGbrEyAqZE+5UdF104VlMrYigF/Jbgo=,iv:dFodoTJClFk6eOWbkL9BqgxzRuPADhjXgHNnN5kd1zI=,tag:+v/COOg+RAp+ur1OfqyNyA==,type:str]
  token: ENC[AES256_GCM,data:LEoSQYjyjGOnRsqXuGfAQFo4hqAlb/0apueYZHJXyLAczDMC1D7242IdwWUYYLRIrS2sPJjuQ8nSueWjg5mkl+zfg63WB92iIahVb9QXb6kzydPZ/OucOXq9iJIWMN3UhsKfLQH9kogOXURviGrgOskBIFCbmX32ku1M6Ev6sTnn+d3ufkKFQOQx+FPNfqSKxKDJByaFqs0VZepVWZeCFjVURACfKAN2Hw8m3gtjf//iw2GF0XIl0gl2zAWnS/A3GVYpj6Rv1hvgvrAHnNVtqHQ+d03bgmhsK2K1bs0j/Xk7WRRvgy2xDK70pFkp1bKeAYjuZj3gaoRtP/dz99Ip0eh/KrbEumspWfHbvhrZBp+q3xfFMBzBSaKj/Kj26RmdQPUH6MtXrWczoHgBFQWH+nL6TOiJvUOhec6yoN9FBvHgKiEo9PXdulYnlmzZ4dtwZaP55lWR2cnY9XR2B+OtXoHDqpNlnhroSq6IAw8b3ZwNEZk8f+c6279/paUBR8PsYJ/YB7iGHasx6+2aO5YFBBXf/TLXbGXQ3CLa/VQwpfrvbpl3kNuHnq4K4oPS/ARGATi+futdvfCh+04TmdoNvsjw2/3WTPXxDy4FN1NThWAVmeaYBaTU0xsyLq6TgGXTg3nKfmWFFSQFegnJxVSR8rSIPSEtMGWODQU7R/Btops4eBmoHUlxa6d0mJlAU4/xKyVUJHzYDy0hCbVY2Vhc5YKxC3Aiy+kkCWHUEQwnV24BKkyr5NvEJqqJ/GSRRla6ppCvub0SDlhCg9plE/z1GDAaAYtRjm4EoBMGJBo7DGVS3A3RVH3J8tOMiPxF3RDys+ZlvH/Wz49Pe9vVcIg4OHTS,iv:dXoRhFXXcQs00FmFy3tjoWeuX4eHJE48evgkr2VKJYM=,tag:KJxMR3KOuEMMV1bD0ZjokQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSnE1UFdKZjlYVUdLTzN6
        RXFrc0xWSGNUTXIxRG82ZVduMzk1bWk0QlZzClF6a25xY2tzQXBvOWFSUDN0SG9U
        dUozenhmc1BJYzE4OWU5TWdmdjN6MDAKLS0tIFIvaEtLYkM0UTFYcDFYd25NQmF3
        VVQyanJ3UDBjazllZmU2ZDUzUDlzYmsKzPcNBIXo6mZt2eBohzAl+0lSsvqhk3Dz
        l16QQs7wt+qX4NbjTxwcqgC823isuLijXAep77ZEbUn+lE2fIppCxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ryhy9dduzk5hyn33lnm7swtg72r7luklfv397s3wmhqav099w95s3cu3rh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-18T18:38:38Z"
  mac: ENC[AES256_GCM,data:TnsXlIiRwWEGuZzsypBj9lapk99u/TBJpcPm/ma4KO/DaK4VMoPz+7NoKkjgFt+BGlaGEIZDP+ZaLcS+vxgBzSaHku2hZN9mhrFNVbkz9dGMJ7nVlVlIEEzgJiXD9CdyZeIPFNkNPW8vPlPd8sPQSqkiJIzKOqbKsmZ1VIKUY8k=,iv:e2FlwV/yie6E1a/tPugSMd2MOjE7DOc7O18cxXWNtjE=,tag:n0gl9oxeto6bNSU0nSz0GA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
