apiVersion: v1
kind: Secret
metadata:
  name: onepassword-token
  namespace: kube-system
stringData:
  token: ENC[AES256_GCM,data:Xb5NRM0Oa/2UFnhzbjEV8fG3Bvh5+v0Lidm6q012pY55qkr0E7GXqscr3mL+omAXodlZhlmiqWh/FfLceQS3gldm4c/4R0ZXQScd8srFOlUYsRIugEU92NgJmlGhPvLIVjx3sttCCBtXmCH0uDjrPIHDITV3TaaSckj8Gmna2gM3W5gugGhkU6c3/EHbmXTr6ERrN2wBkpFiX5N/sBxfGF+RG78fxoPzH2IEOa4RUTEbzBirfHP2CAAP8gGh5MS9PsKL1ARhXtGytdaMMW5B1Ss8dzvOQYJQk2epIK9Rl+AfPunWfEg1P9ct3YDJBsQMgCEPz8DUibndWERw1LBOH0IEqFLLtb9MMs20rBGzefZzTr5LQZtUxqTwxteXk5l4UvvwgQKRdDiLn9mWIXrJor+hHwsqpT7pu3Pru88i1rwpQrHycFRcXn3soJlYRTT4OuzfL2KWucN0ZdHmjWtUtyxXWi9iRatmR9OYNpKpuetUbcdmFacGwdbHwtBQ4qJxG/DfKoce7u+lRWKfeJ1UegEgqMQbTV6FdlEUiF5OPPomsccC8777eQ+T8NLvnHxrYlTGIzsTn4d1zuAQT4KYa+aWKu481qL0Rr4Fzw9PAoiA8ooFtl6ky1yb7cCNtTjvj4N4vAVnAImreIjG4dG2INY5RVP3PelELGFbdPfxWudN6N7G9sEeQwJIRrN41shmQiKot9XnQFlRuUl1C/qhL73pdYU9A6WIIiWDom5d1r0BRC4aSTmhS9AveCVO2VsDPds4CWLHDEDFLE/Y+rAS5inAVsLdCHd+/EjocDsTVCJ4ZwodwgAJ3W8wX8Vi8PtjNXM8csSbJVDLd0vWE2KuBF8wqJLyLLHAkR3t1+zehS92aI4f0O4joWnpVvcpOeRUNkDqtBJP/zHid7l6ksN3D+Dr9ehT3YFInmpNjYOAARUIfoaEjQfkwuI8r9/Cbbj2CX0xTSKaN/ALU6d0xl8GWju+2BnrOxPAaQNhBsdrY3bf5BwSxlm9F2giKqADd57ww/LgwtfQHBNly0VTMq3gdnQ4AZgWAhDgMEwZpHY2LgsX90l7mrSOOECszyxaIpHu27x7mZ7yQiGm44SFvkXVz++zjeXZoCPFvdNMmie5+35LB4Uy,iv:4ZvBIpZrevPyECyYkM5xvCshn9FOuxNH21E4HKxot2E=,tag:BsCzfWMoRggZgu+rOe7EUQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MEJJbEw3SGtncndyUXlT
        OFhsWldYTEtKdmpGTkFEVVY2Z0R6UjQ4R3lzCnY0WVVUb29PVDhQZCtmeWZNOXlJ
        eG5yL0drSjNRV1N2R0FvRDJkazIwQ2cKLS0tIFFIQ1R0dGhTMkdOMzNseFFoNjhu
        cmVKV3U2L041c045TDN2SElQSHJQQ2cKbu29Gd73bxs2WKagM/WBUA2Ryldgeshu
        k77fSPwbl0uG+JBseTKcWRJxum7GQDZq4qR3/xQz7/C6ZbOa7mExzQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ryhy9dduzk5hyn33lnm7swtg72r7luklfv397s3wmhqav099w95s3cu3rh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-18T20:29:17Z"
  mac: ENC[AES256_GCM,data:HOAkrZGhFrDdTDvwuTElqjJtLWD6QTH7kN16cEeh3Yn0aaBEq/rA660dv6kSNtwPWXGTXg22HVFSSzdEZo2DvuhRsbiIf6ex+EDs6twiX6ZdHEmyQMNYD7e+95CdMy8/oznzHQPsMm4DVgoXKkde19GZtGfC1QnG9yCDEIQALdw=,iv:t2mO/Hdfuu15z2yOcyVcDS0chRSGb9s7iZcdtxrxyKM=,tag:1DnkH4MLuyZDFbXhKgEW1g==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
