---
apiVersion: v1
kind: ConfigMap
metadata:
  name: truenas-nginx-config
  namespace: external
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 8080;
        location / {
          proxy_pass https://192.168.69.69:443;
          proxy_ssl_verify off;
          proxy_http_version 1.1;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_read_timeout 3600s;
          proxy_send_timeout 3600s;
          proxy_buffering off;
        }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: truenas-nginx
  namespace: external
  annotations:
    glance/show: "true"
    glance/name: TrueNAS
    glance/icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/truenas-scale.png
    glance/description: "Network-attached storage management."
  labels:
    app.kubernetes.io/name: truenas-nginx
    app.kubernetes.io/instance: truenas-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: truenas-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: truenas-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.31-alpine
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config
          configMap:
            name: truenas-nginx-config
