---
apiVersion: v1
kind: Service
metadata:
  name: &app truenas
  namespace: external
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      targetPort: 80

---
apiVersion: v1
kind: Endpoints
metadata:
  name: &app truenas
  namespace: external
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
subsets:
  - addresses:
      - ip: 192.168.69.69
    ports:
      - port: 80
