name: 🐛 Bug Report
description: Something is broken in the cluster
title: "🐛 [Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: textarea
    id: what-happened
    attributes:
      label: What's broken?
      description: Describe what's not working as expected
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: dropdown
    id: affected-app
    attributes:
      label: Which app/service is affected?
      options:
        - Grafana
        - Prometheus
        - Plex
        - Sonarr/Radarr/Prowlarr
        - Authentik
        - Database (PostgreSQL/Dragonfly)
        - Networking (Cilium/Cloudflare)
        - Storage (Ceph/VolSync)
        - Multiple apps
        - Cluster infrastructure
        - Other
    validations:
      required: true

  - type: input
    id: namespace
    attributes:
      label: Namespace
      description: Which namespace is affected?
      placeholder: e.g., media, observability, default

  - type: textarea
    id: expected
    attributes:
      label: What should happen instead?
      description: What did you expect to work?
      placeholder: Expected behavior...

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or error messages
      description: Any error messages, logs, or screenshots
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Anything else that might help debug this
      placeholder: Recent changes, when it started, etc.
