---
apiVersion: v1
kind: Endpoints
metadata:
  name: etcd-metrics
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.69.110
      - ip: 192.168.69.111
      - ip: 192.168.69.112
    ports:
      - name: metrics
        port: 2381
        protocol: TCP
