---
apiVersion: v1
kind: Service
metadata:
  name: etcd-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/component: control-plane
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 2381
      protocol: TCP
