---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komga-restic
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: komga-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .REPOSITORY_TEMPLATE }}/komga"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: volsync-restic-template
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: komga
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: komga
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: komga
spec:
  trigger:
    manual: restore-once
  restic:
    repository: komga-restic-secret
    copyMethod: Snapshot
    accessModes: ["ReadWriteOnce"]
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheAccessModes: ["ReadWriteOnce"]
    cacheCapacity: 4Gi
    cacheStorageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    capacity: 1Gi # must match the PersistentVolumeClaim `.resources.requests.storage` size above
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: komga
spec:
  sourcePVC: komga
  trigger:
    schedule: "15 */8 * * *"
  restic:
    pruneIntervalDays: 7
    repository: komga-restic-secret
    copyMethod: Snapshot
    accessModes: ["ReadWriteOnce"]
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheAccessModes: ["ReadWriteOnce"]
    cacheCapacity: 1Gi
    cacheStorageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      hourly: 24
      daily: 7
      weekly: 5
