---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-backup
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      postgres-backup:
        type: cronjob
        cronjob:
          schedule: "0 3 1,15 * *"
          concurrencyPolicy: Forbid
          ttlSecondsAfterFinished: 43200
        pod:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
        containers:
          app:
            image:
              repository: mirror.gcr.io/prodrigestivill/postgres-backup-local
              tag: 18@sha256:f70742ebe42b2277689b028d1fd15aa80f77cffa01da163cc9f85a6ff1866e7f
            command:
              - /bin/bash
              - -x
              - /backup.sh
            env:
              TZ: Europe/Paris
              POSTGRES_HOST: db.internal
              POSTGRES_PORT: "5432"
              POSTGRES_DB: "atuin,docmost,gatus,prowlarr_main,radarr_main,seerr,sonarr_main"
            envFrom:
              - secretRef:
                  name: pgbackup-secret
    persistence:
      nas:
        type: nfs
        server: nas.internal
        path: /mnt/storage0/pgbackup
        globalMounts:
          - path: /backups
