---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-backup
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      postgres-backup:
        type: cronjob
        cronjob:
          schedule: "@weekly"
          ttlSecondsAfterFinished: 43200
        pod:
          restartPolicy: OnFailure
        containers:
          app:
            image:
              repository: ghcr.io/axeii/pgbackup
              tag: v3@sha256:247b274e2603070aae467351106cd3fb3fdfad0edf9185ff77201eaf1b6d907c
            envFrom:
              - secretRef:
                  name: pgbackup-secret
