---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: piped
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: piped-db-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_DATABASE_NAME: &dbName "{{ .PIPED_DB_NAME }}"
        DB_HOSTNAME: &dbHost ${DATABASE_IP}
        DB_USERNAME: &dbUsername "{{ .PIPED_DB_USERNAME }}"
        DB_PASSWORD: &dbPassword "{{ .PIPED_DB_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUsername
        INIT_POSTGRES_PASS: *dbPassword
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: piped
    - extract:
        key: cloudnative-pg
