---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: piped
  namespace: default
  annotations:
    redeploy: "2024-09-15T22:11:05Z"
spec:
  interval: 15m
  chart:
    spec:
      chart: piped
      version: 7.4.1
      sourceRef:
        kind: HelmRepository
        name: piped
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    postgresql:
      enabled: false
    frontend:
      image:
        repository: "docker.io/1337kavin/piped-frontend"
        tag: "latest"
        pullPolicy: Always
      env:
        BACKEND_HOSTNAME: &api_host papi.${SECRET_DOMAIN}
        TZ: ${TIMEZONE}

    backend:
      podAnnotations:
        configmap.reloader.stakater.com/reload: "piped-backend-config"
      initContainers:
        01-init-db:
          image: ghcr.io/onedr0p/postgres-init:16
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: &secret piped-db-creds
      image:
        repository: "docker.io/1337kavin/piped"
        tag: "latest"
        pullPolicy: Always
      env:
        TZ: ${TIMEZONE}
      config:
        PORT: 8080
        HTTP_WORKERS: 4
        PROXY_PART: https://pproxy.${SECRET_DOMAIN}
        # DISABLE_REGISTRATION: false
        database:
          connection_url: jdbc:postgresql://${DATABASE_IP}/piped
          secret:
            name: *secret
            username: DB_USERNAME
            password: DB_PASSWORD

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: mdi:youtube
          hajimari.io/enable: "false"
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://yt.${SECRET_DOMAIN}, https://pproxy.${SECRET_DOMAIN}, https://papi.${SECRET_DOMAIN}"
        hosts:
          - host: &host yt.${SECRET_DOMAIN}
            paths:
              - path: "/"
        tls:
          - hosts:
              - *host
      backend:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "false"
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS HEAD"
          nginx.ingress.kubernetes.io/cors-allow-origin: "*"
        hosts:
          - host: *api_host
            paths:
              - path: "/"
        tls:
          - hosts:
              - *api_host
      ytproxy:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "false"
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://yt.${SECRET_DOMAIN}, https://pproxy.${SECRET_DOMAIN}, https://papi.${SECRET_DOMAIN}"
        hosts:
          - host: &proxy pproxy.${SECRET_DOMAIN}
            paths:
              - path: "/"
        tls:
          - hosts:
              - *proxy
