---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: thanos
      version: 14.0.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: public.ecr.aws
      repository: bitnami/thanos
    query:
      enabled: true
      repliaceCount: 1
      replicaLabels:
        - replica
      dnsDiscovery:
        sidecarsService: prometheus-thanos-discovery
        sidecarsNamespace: monitoring
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          hajimari.io/instance: "bloop-quarky"
          hajimari.io/appName: "Thanos"
        hosts:
          - host: &host "thanos.${SECRET_DOMAIN}"
            paths:
              - "/"
        tls:
          - hosts:
              - *host
            secretName: "tls.thanos"
    existingObjstoreSecret: thanos-objstore

    queryFrontend:
      enabled: false

    bucketweb:
      enabled: true
      ingress:
        enabled: true
        hostname: &hostbweb "thanos-bucketweb.${SECRET_DOMAIN}"
        ingressClassName: nginx
        tls: true
        extraTls:
          - hosts:
              - *hostbweb
            secretName: tls.thanos-bucketweb

    compactor:
      enabled: true
      ingress:
        enabled: true
        hostname: &hostcompact "thanos-compactor.${SECRET_DOMAIN}"
        ingressClassName: nginx
        tls: true
        extraTls:
          - hosts:
              - *hostcompact
            secretName: tls.thanos-compactor
      persistence:
        enabled: false

    storegateway:
      enabled: true
      ingress:
        enabled: true
        hostname: &hostgateway "thanos-storegateway.${SECRET_DOMAIN}"
        ingressClassName: nginx
        tls: true
        extraTls:
          - hosts:
              - *hostgateway
            secretName: tls.thanos-storegateway
      persistence:
        storageClass: "longhorn"
        accessModes:
          - ReadWriteOnce
        enabled: true
        size: 3Gi

    ruler:
      enabled: true
      dnsDiscovery:
        enabled: true
      alertmanagers:
        - http://kube-prometheus-stack-alertmanager.monitoring:9093
      clusterName: ${CLUSTER_NAME}
      extraFlags:
        - "--web.prefix-header=X-Forwarded-Prefix"
      config: |-
        groups:
          - name: "PrometheusWatcher"
            rules:
              - alert: "PrometheusDown"
                expr: absent(up{job="kube-prometheus-stack-prometheus"})
      ingress:
        enabled: true
        hostname: &hostruler "thanos-ruler.${SECRET_DOMAIN}"
        ingressClassName: nginx
        tls: true
        extraTls:
          - hosts:
              - *hostruler
            secretName: tls.thanos-ruler
      persistence:
        enabled: true
        storageClass: "longhorn"
        size: 250Mi

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
