---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app epic-freegames
  namespace: default
spec:
  interval: 15m
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    image:
      repository: ghcr.io/claabs/epicgames-freegames-node
      tag: latest@sha256:493d039af91b13cabe4b4d5a51d7a8ed789f21697e6fdb07d6a00dd1a7c9639b

    envFrom:
      - secretRef:
          name: epic-freegames-secret

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "epic.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    persistence:
      data:
        enabled: true
        existingClaim: epic-freegames-config
        mountPath: /usr/app/config
        retain: true

    probes:
      startup:
        enabled: false
      readiness:
        enabled: false
      liveness:
        enabled: false
