---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-ceph-mon
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes
  target:
    name: rook-ceph-mon
    creationPolicy: Owner
  data:
    - secretKey: ceph-secret
      remoteRef:
        key: rook-ceph-mon
        property: ceph-secret
    - secretKey: ceph-username
      remoteRef:
        key: rook-ceph-mon
        property: ceph-username
    - secretKey: fsid
      remoteRef:
        key: rook-ceph-mon
        property: fsid
    - secretKey: mon-secret
      remoteRef:
        key: rook-ceph-mon
        property: mon-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-ceph-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes
  target:
    name: rook-ceph-config
    creationPolicy: Owner
  data:
    - secretKey: mon_host
      remoteRef:
        key: rook-ceph-config
        property: mon_host
    - secretKey: mon_initial_members
      remoteRef:
        key: rook-ceph-config
        property: mon_initial_members
