apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-mon
type: kubernetes.io/rook
stringData:
  ceph-secret: ENC[AES256_GCM,data:oCQ3uHC6N9fqAMyy5jOCn0Pzvb4S/mjHUNb1zXLtIA0A8N8lBQQCHg==,iv:y+eJqvO40ieI0NQo+yPNEuRkzqi7XsfRa6lPgJZmfCo=,tag:YfjrCgdgbwFO47MwlYb1SA==,type:str]
  ceph-username: ENC[AES256_GCM,data:1KzbateLQ+i37qy4,iv:xjTW+XxIf/KMUxNGHai+Wicm9anKSjGkErWHp8ibaYY=,tag:fvBj5zfM3733+CU48vnidw==,type:str]
  fsid: ENC[AES256_GCM,data:8xgXZi+YH2svlH0jSrMkCIkchGNzSWZkgnQasgMBB21EAz7g,iv:F3uwDlj+1q6KUKYVhTPWi0PHcR4Io2qXGFCy01o2gUE=,tag:GVXN62g9xPqf7LxnsJS7bw==,type:str]
  mon-secret: ENC[AES256_GCM,data:2SbxOK73xBsjBzEBNy2Y/bHSykJU7uI+ywktXLFdcRt8vy4oov+AmA==,iv:qQNYswGt9oCaNxvHUzZCN8V2Ly3B2mAGA4tFSY9c7lA=,tag:Ba0dGPZxWn1SElXUt10htQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMV3BYSFhTNXVXMHF6MzF1
        Y3FEdGltaTUvc0lhUnFKUHhMQzJtcC9JQlNnClYyajl1UCtVOUxlbGFaVC94N3Bh
        dWU3Skh5a1ZDTnB0OTd6dG9FNjFtbW8KLS0tIDZmNUpNZm5LSHRxZUlDSDNoSXhZ
        KzA4bmJjTXArTkZvMVFoS08xSzFoTWMKOze2M2iTjTSpkBLOevA6D9cX33m7oWZv
        HBV71Lr8yVX6CM4Kq0lBJaaGtlA6cSntIDo3EwAN3793ytbv9+JeKA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ryhy9dduzk5hyn33lnm7swtg72r7luklfv397s3wmhqav099w95s3cu3rh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-18T22:18:26Z"
  mac: ENC[AES256_GCM,data:md5I/FEMQ+qsZnjqBNbD8Au+KmxTlFs4G/Sb7+OY+UsOomJ/OELtsRjKkZLUBEQftNj3vriih5BDaD+ZQKx3NzbognTLs6mkNMg64xCMjf0NLvYziMlZ8jArSLlqSAakLO+z+9lKhOQ1K0ONtX26UC2edjhDcldxSHEP0fXKb18=,iv:ZrFuQQht/n1XPgUBocN84tOcBmtEElcXZk2io5DN/+0=,tag:hnBkPrB1UpNWfmdZxAFnPQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-config
type: kubernetes.io/rook
stringData:
  mon_host: ENC[AES256_GCM,data:e2t/e+Rsc8OyWJn0XEyBTawlMkdk4Wi594Jtxh+gUnQVUR865K/azd6ruf4Mn468biKhuTVaNEMQlHaiUyQBSFJ8oCKV2ZMkVFo=,iv:pg/4/ZTVn2uFkTQNLaV5uziNlbGE4w4UBX+yeJmWWTs=,tag:XsoCs/Ofe80XauG1HjoiBg==,type:str]
  mon_initial_members: ENC[AES256_GCM,data:Vcq/c9w=,iv:YVqhlGOZzeICAunoEMXzgy7n96lGQSatZIOiSdZugBk=,tag:TGLAVoObhbU9zrIyWIZ0cA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMV3BYSFhTNXVXMHF6MzF1
        Y3FEdGltaTUvc0lhUnFKUHhMQzJtcC9JQlNnClYyajl1UCtVOUxlbGFaVC94N3Bh
        dWU3Skh5a1ZDTnB0OTd6dG9FNjFtbW8KLS0tIDZmNUpNZm5LSHRxZUlDSDNoSXhZ
        KzA4bmJjTXArTkZvMVFoS08xSzFoTWMKOze2M2iTjTSpkBLOevA6D9cX33m7oWZv
        HBV71Lr8yVX6CM4Kq0lBJaaGtlA6cSntIDo3EwAN3793ytbv9+JeKA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ryhy9dduzk5hyn33lnm7swtg72r7luklfv397s3wmhqav099w95s3cu3rh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-18T22:18:26Z"
  mac: ENC[AES256_GCM,data:md5I/FEMQ+qsZnjqBNbD8Au+KmxTlFs4G/Sb7+OY+UsOomJ/OELtsRjKkZLUBEQftNj3vriih5BDaD+ZQKx3NzbognTLs6mkNMg64xCMjf0NLvYziMlZ8jArSLlqSAakLO+z+9lKhOQ1K0ONtX26UC2edjhDcldxSHEP0fXKb18=,iv:ZrFuQQht/n1XPgUBocN84tOcBmtEElcXZk2io5DN/+0=,tag:hnBkPrB1UpNWfmdZxAFnPQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
