apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-mon
type: kubernetes.io/rook
stringData:
  ceph-secret: ENC[AES256_GCM,data:2oFZllTp0cT39a1QqKVeyz0PYlCRnLDcFGOTqE6GKRSnUOVgBB84Dz6KtuuLT9cmIjCRk2fIsDt7n/Oj,iv:uIuQNTzHJh8pNU273gG8evEBqCCKoYMLBebpE811vhY=,tag:0+SHEDyDTiRXzLv/b/EU6Q==,type:str]
  ceph-username: ENC[AES256_GCM,data:bjwzgPFTRKEyG54w,iv:y7xdkadn88Q8a4LXxkzZmu3t0aLpE58tCziaQ5pFeA0=,tag:HYgPS7qP3DZLwmpVgKtl/g==,type:str]
  fsid: ENC[AES256_GCM,data:qT7zGiJ9M+UXss0+if577HFfIL74VuVMSiUeDEE9gWrGx6DO,iv:ZxCYVkE/SSqsYyEDk9jRsqDdTa0NiS0PDAF8ENMJ03E=,tag:H56uW+jLSnCI7yJuN7nYKw==,type:str]
  mon-secret: ENC[AES256_GCM,data:a1pZrTV5TQQir3ai0YI2IUL9qe3MOMA4dTWBWfp47E6H8hNqfoWk536leelWnriX71bquFX5SQBn7WX2,iv:td1DMVTJZzWyC8t2MQpWK43YqBhdpDKDqdNVF4P5Zgg=,tag:HqUU1O8zuGVdzkjoxgKO1Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBib0owdnZSVk5kU1pwNmFy
        VGVkWlBsaisrRTJHalJ6WnFkVW4vZGRGRVVvCmVrUytPdXVwYXRBT0dMN3BPZzlx
        ejgzOTV2RmxwLzVZcExNTXRjeElETUEKLS0tIG8zMGlIbXNqWjd1SjB2d0JKUFlY
        OEY3SHlaOHhIT0s5VEZBK0E2ZmZJK1UKrQR//EpzIoVuCzculQ/exsoFg9SZd47X
        c4N2T2Isy5vZb3QKXS62w2zWbzmrLMw1Yszhx1RGeCJT2Aqe3Fpfww==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ryhy9dduzk5hyn33lnm7swtg72r7luklfv397s3wmhqav099w95s3cu3rh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T14:14:00Z"
  mac: ENC[AES256_GCM,data:BhhAK1oVFWnGlFukaqG3dRYegtWiQa8cYYdu8ha4WGp39RG0wm1S2mjGdMFs9u5LICrl2N36u6bvmEMnZBRyC6JBAFFZiXSyaEIQi+FXaDMze/tt/yuRbP0CyDKvpIqSdL5yo0AGkxwM3DTqOQNva2HBYK4JnP6IqG7MAyGUm6U=,iv:mjY2dU93uMrfrv4qhe+UtXtPsZ1SixjhEuv0v6h+qOA=,tag:zxLDCc+IXxt5ajO9wEX8Nw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-config
type: kubernetes.io/rook
stringData:
  mon_host: ENC[AES256_GCM,data:OrMbVxNHddf0KM2jxhkTNRAbUbSbRVAy3fYKl2CZQuTdP1IWILwYNUVszGwYsAlZUwBt7PxvgI8v498CRHZIYnLixx3m1XEnglw=,iv:4PZ+HslcuRYP+Xjni8P3j1t02Z3LfSzYjjbWqLzh28Q=,tag:jHiCimqn9qYJ47iNCaZR+w==,type:str]
  mon_initial_members: ENC[AES256_GCM,data:BIsnzU0=,iv:7m75T5V6ebeqJl1BVLOTVO1uekDbUn/v30CjTVUNcJc=,tag:p+3Yc5GkVFvBJB0jMrrQQA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBib0owdnZSVk5kU1pwNmFy
        VGVkWlBsaisrRTJHalJ6WnFkVW4vZGRGRVVvCmVrUytPdXVwYXRBT0dMN3BPZzlx
        ejgzOTV2RmxwLzVZcExNTXRjeElETUEKLS0tIG8zMGlIbXNqWjd1SjB2d0JKUFlY
        OEY3SHlaOHhIT0s5VEZBK0E2ZmZJK1UKrQR//EpzIoVuCzculQ/exsoFg9SZd47X
        c4N2T2Isy5vZb3QKXS62w2zWbzmrLMw1Yszhx1RGeCJT2Aqe3Fpfww==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ryhy9dduzk5hyn33lnm7swtg72r7luklfv397s3wmhqav099w95s3cu3rh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T14:14:00Z"
  mac: ENC[AES256_GCM,data:BhhAK1oVFWnGlFukaqG3dRYegtWiQa8cYYdu8ha4WGp39RG0wm1S2mjGdMFs9u5LICrl2N36u6bvmEMnZBRyC6JBAFFZiXSyaEIQi+FXaDMze/tt/yuRbP0CyDKvpIqSdL5yo0AGkxwM3DTqOQNva2HBYK4JnP6IqG7MAyGUm6U=,iv:mjY2dU93uMrfrv4qhe+UtXtPsZ1SixjhEuv0v6h+qOA=,tag:zxLDCc+IXxt5ajO9wEX8Nw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
