---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tuppr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tuppr-notification
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        url: "pushover://shoutrrr:{{ .GATUS_PUSHOVER_TOKEN }}@{{ .PUSHOVER_USER_KEY }}/"
  dataFrom:
    - extract:
        key: pushover
