---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tuppr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: tuppr
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controller:
      logLevel: info
      leaderElection:
        enabled: true
      metrics:
        enabled: true
    webhook:
      enabled: true
    notification:
      enabled: false
    monitoring:
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
      dashboards:
        enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi
