---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-truenas
  namespace: external
spec:
  dependsOn:
    - name: ingress-nginx-internal
  path: ./kubernetes/apps/external/truenas/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: v1
      kind: Service
      name: truenas
      namespace: external
  interval: 30m
  retryInterval: 1m
  timeout: 3m
