---
# yaml-language-server: $schema=https://raw.githubusercontent.com/axeII/crds/main/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app kavita
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    controllers:
      kavita:
        labels:
          nfsMount: "true"
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: jvmilazz0/kavita
              tag: 0.8.6@sha256:cdd6abc6e5c3d337c5bb68d4a29bc490456af2a550b3a031374e46dbfac291ce
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 15m
                memory: 300Mi
              limits:
                memory: 1Gi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 5000
    ingress:
      app:
        className: nginx
        annotations:
          gatus.io/enabled: "true"
          hajimari.io/icon: "notebook-heart"
          hajimari.io/group: "media"
          # gethomepage.dev/enabled: "true"
          # gethomepage.dev/group: Books
          # gethomepage.dev/name: Kavita
          # gethomepage.dev/icon: kavita.png
          # gethomepage.dev/description: Comic/Ebook Web Reader
          # gethomepage.dev/widget.type: kavita
          # gethomepage.dev/widget.url: http://kavita.media:5000
          # gethomepage.dev/widget.username: "{{HOMEPAGE_VAR_KAVITA_USERNAME}}"
          # gethomepage.dev/widget.password: "{{HOMEPAGE_VAR_KAVITA_PASSWORD}}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]
    persistence:
      config:
        existingClaim: kavita-config-v1
        globalMounts:
          - path: /kavita/config
      media:
        type: nfs
        server: 192.168.69.69
        path: /mnt/ThiccBoi/SiccBoi/data/media/Literature
        globalMounts:
          - path: /data
