---
alerting:
  pushover:
    application-token: ${GATUS_PUSHOVER_APP_TOKEN}
    user-key: ${GATUS_PUSHOVER_USER_KEY}
    priority: 1
    default-alert:
      description: healthcheck failed
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 3

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

metrics: true

storage:
  type: postgres
  path: postgres://${INIT_POSTGRES_USER}:${INIT_POSTGRES_PASS}@${INIT_POSTGRES_HOST}:5432/${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true

ui:
  title: Status | Gatus
  header: Status
  logo: https://i.imgur.com/gdvBkNE.png 
  link: https://github.com/axeII
  buttons:
    - name: Github
      link: https://github.com/axeII
    - name: Homelab
      link: https://github.com/axeII/home-ops

endpoints:
  - name: blog
    group: external
    url: https://axell.dev
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover

  - name: ceph-health
    group: infra
    url: http://rook-ceph-mgr.rook-ceph.svc.cluster.local:9283/metrics
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[BODY] != pat(*ceph_health_status{* 2*)"
    alerts:
      - type: pushover
        description: "Ceph cluster is in HEALTH_ERR"

  - name: flux-health
    group: infra
    url: http://kube-state-metrics.observability.svc.cluster.local:8080/metrics
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[BODY] != pat(*ready=\"False\"*)"
    alerts:
      - type: pushover
        description: "a Flux-managed resource is not Ready"

web:
  port: ${GATUS_WEB_PORT}
