---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app botkube
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: botkube
      version: v1.9.1
      sourceRef:
        kind: HelmRepository
        name: botkube-charts
        namespace: default
      interval: 1m
  values:
    config:
      provider:
        endpoint:
          valueFrom:
            secretKeyRef:
              name: botkube-secret
              key: endpoint
        identifier:
          valueFrom:
            secretKeyRef:
              name: botkube-secret
              key: identifier
        apiKey:
          valueFrom:
            secretKeyRef:
              name: botkube-secret
              key: apiKey
    resources:
      request:
        cpu: 100m
        memory: 64Mi
