---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app plex-music
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      plex-music:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/axeii/chromatix
              tag: v2@sha256:0cc580b8f36df0b780e32b675140b1d99f5e33ccbd27c8dde2ddd75613c0254b
            # env:
            #   HTTP_PORT: &port 80
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 20m
              limits:
                memory: 64Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      logs:
        type: emptyDir
        globalMounts:
          - path: /tmp
    route:
      app:
        annotations:
          glance/name: Music
          glance/show: "true"
          glance/icon: si:applemusic
          glance/description: "Music streaming service for Plex"
        hostnames: ["music.juno.moe"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
