---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mylar
  namespace: media
spec:
  interval: 15m
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
  values:
    image:
      repository: ghcr.io/linuxserver/mylar3
      tag: version-v0.7.2
    env:
      TZ: ${TIMEZONE}
      PUID: "1000"
      PGID: "1000"
    service:
      main:
        ports:
          http:
            port: 8090

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: "simple-icons:mdbook"
        hosts:
          - host: &host "mylarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: mylar-config-pvc
      nfs-nas-media:
        enabled: true
        existingClaim: media-nfs-share-pvc
        mountPath: /media
        readOnly: false
