---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Prague"

  # LAN
  USER_ID: "65534"
  DATABASE_IP: "192.168.69.107"

  # NAS
  NAS_IP: "192.168.69.69"
  NAS_MEDIA_PATH: "/mnt/storage0/media"
