---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: affine
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: affine-secret
    template:
      data:
        DATABASE_URL: postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@${DATABASE_IP}:5432/affine
        INIT_POSTGRES_DBNAME: affine
        INIT_POSTGRES_HOST: ${DATABASE_IP}
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_ENCODING: "UTF8"
        AFFINE_SERVER_HTTPS: "true"
        AFFINE_SERVER_HOST: "nt.juno.moe"
  dataFrom:
    - extract:
        key: affine
    - extract:
        key: cloudnative-pg
