---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app affine
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      affine:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/toeverything/affine-graphql
              tag: canary-a23112c@ sha256:abb0a874b0a6a85918c358d44b8a277fed3c36117e486b41b1409e991ac34cd9
            env:
              TZ: "${TIMEZONE}"
              REDIS_SERVER_HOST: dragonfly.database.svc.cluster.local
            envFrom:
              - secretRef:
                  name: affine-secret
            probes:
              liveness:
                enabled: true
                path: /
                port: &port 3010
              readiness:
                enabled: true
                path: /
                port: *port
            resources:
              requests:
                cpu: 25m
                memory: 105M
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: affine
        ports:
          http:
            port: *port
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: "nt.juno.moe"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      workspace:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /siyuan/workspace
