---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: ceph-node-nfsmount-diskspace-warning
spec:
  matchers:
    - name: alertname
      value: CephNodeDiskspaceWarning
    - name: mountpoint
      value: /etc/nfsmount.conf
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: ceph-node-local-diskspace-warning
spec:
  matchers:
    - name: alertname
      value: CephNodeDiskspaceWarning
    - name: device
      value: /dev/sd.*
      matchType: "=~"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: ceph-node-network-packet-drops
spec:
  matchers:
    - name: alertname
      value: CephNodeNetworkPacketDrops
      matchType: "="
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: ceph-node-network-packet-errors
spec:
  matchers:
    - name: alertname
      value: CephNodeNetworkPacketErrors
      matchType: "="
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: keda-hpa-maxed-out
spec:
  matchers:
    - name: alertname
      value: KubeHpaMaxedOut
    - name: horizontalpodautoscaler
      value: keda-hpa-.*
      matchType: "=~"
