---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-debug
spec:
  containers:
    - name: debug
      image: busybox
      command: ['sh', '-c', 'echo Lets debug! && sleep 3600']
  #     volumeMounts:
  #       - name: volume-claim
  #         mountPath: "/data"
  # volumes:
  #   - name: volume-claim
  #     persistentVolumeClaim:
  #       claimName: appdata # CHANGE THIS TO YOUR PVC NAME
  restartPolicy: Never
