---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-readarr
  namespace: flux-system
spec:
  targetNamespace: media
  dependsOn:
    - name: longhorn
    - name: cluster-apps-external-secrets-stores
  path: ./kubernetes/apps/media/readarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
