---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external
components:
  - ../../components/common
resources:
  - ./truenas/ks.yaml
  - ./minio/ks.yaml
  - ./proxmox/ks.yaml
