---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: seafile
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://phybros.github.io/helm-charts
      chart: seafile
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: phybros-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: seafileltd/seafile-mc
      tag: 11.0.13
    env:
      TIME_ZONE: ${TIMEZONE}
      SEAFILE_SERVER_HOSTNAME: "files.${SECRET_DOMAIN}"
      SEAFILE_ADMIN_EMAIL: "${SECRET_MY_EMAIL}"
      SEAFILE_ADMIN_PASSWORD: "${SECRET_SEAFILE_ADMIN_PASSWORD}"
      DB_HOST: "192.168.69.104"
      DB_NAME: "seafile"
      DB_ROOT_PASSWD: "${SECRET_DB_ROOT_PASSWORD}"

    persistence:
      shared:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.69.69
            path: /mnt/ThiccBoi/media
        mountPath: /shared

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: "simple-icons:icloud"
          hajimari.io/group: "media"
        hosts:
          - host: &host "files.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    mariadb:
      enabled: false

    # FIXME: I should fix the permissions
    # securityContext:
    #   runAsUser: 1000
    #   runAsGroup: 568
    # podSecurityContext:
    #   fsGroup: 568
    #   fsGroupChangePolicy: "OnRootMismatch"
    #   supplementalGroups:
    #     - 100
