---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wikijs
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: ghcr.io/requarks/wiki
      pullPolicy: IfNotPresent
      tag: "2.5.307"
    env:
      TZ: ${TIMEZONE}
      APP_URL: "https://docs.${SECRET_DOMAIN}"
      DB_TYPE: mysql
      DB_HOST: 192.168.69.104
      DB_PORT: 3306
      DB_NAME: wikijs
      DB_USER: wikijs
      DB_PASS: ${SECRET_WIKIJS_DATABASE_PASSWORD}
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/name: "wiki.js"
          hajimari.io/icon: "wikipedia"
          hajimari.io/description: "A modern and powerful wiki app built on Node.js."
        hosts:
          - host: &host "info.${SECRET_DOMAIN}"
            paths:
              - path: /
                type: Prefix
          - host: &host-custom "wiki.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
              - *host-custom
    resources:
      requests:
        memory: 150M
      limits:
        memory: 2000M
