---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app hajimari
  namespace: &namespace default
spec:
  targetNamespace: default
  path: ./kubernetes/apps/default/hajimari/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: *app
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
