---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tautulli
  namespace: flux-system
spec:
  targetNamespace: media
  dependsOn:
    - name: rook-ceph
  path: ./kubernetes/apps/media/tautulli/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  components:
    - ../../../componens/volsync/
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 3Gi
