---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ca
  namespace: external
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBpTCCAUqgAwIBAgIRAJ2gid6cUiMK1Ep9Tcsne7YwCgYIKoZIzj0EAwIwMDEu
    MCwGA1UEAxMlQ2FkZHkgTG9jYWwgQXV0aG9yaXR5IC0gMjAyNiBFQ0MgUm9vdDAe
    Fw0yNjA3MTUyMTQwMTlaFw0zNjA1MjMyMTQwMTlaMDAxLjAsBgNVBAMTJUNhZGR5
    IExvY2FsIEF1dGhvcml0eSAtIDIwMjYgRUNDIFJvb3QwWTATBgcqhkjOPQIBBggq
    hkjOPQMBBwNCAAQz0lolMCOc4cIW3qQ4NOWL2t6wXTCugKdMHE8XPRK9YIDSgerU
    OApvKww9D/8fe7sEBfk/+CSQ+R2u+cz/fTNAo0UwQzAOBgNVHQ8BAf8EBAMCAQYw
    EgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQUFySclHjPEKwo8SCr1JzpRspY
    JCUwCgYIKoZIzj0EAwIDSQAwRgIhAPi8MznvQJVeUfw+Zjz7kVSNMnqugT/CLrIW
    NZHApur/AiEA5criao1kc8RHAgtIxqXlSBTxCZetzxXgh3iQ7Mb806A=
    -----END CERTIFICATE-----
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: grafana-tls
  namespace: external
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: grafana
  validation:
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: grafana-ca
    hostname: grafana.internal
