apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:w5O25ZmMMkQ=,iv:pjlQ4ewui8ngKjzyEaPG+9qor2HZHSUZZhjsmSj3up8=,tag:oGK70Wgn9Uuwy+TmizqdLA==,type:str]
sops:
  age:
    - recipient: age1ryhy9dduzk5hyn33lnm7swtg72r7luklfv397s3wmhqav099w95s3cu3rh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXR0hwbkhhNjZzWjk5S1Jl
        VjZZeXhzdzZraEJvVGo2QWs5NmsvTlRXQWtvCmdabW1lK1NubHJsVGNrVU0wOUpR
        WmJLK2M2a2NNREF1em05UWorRklOZkUKLS0tIGM1bU5OTGZGWmE5dVh4SFhiTFdw
        UlYxeW5LSzFMNG4wZkhvdG9DNXZCWW8Ku7X8atyZG60bxcgQJ0euV3+M2Lmwg4/R
        ZVFTw4VHBIpcPflCiCCAFoaXgjzarXRP6d7LwK/iEciN8y/Lf/ZrHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-28T00:09:47Z"
  mac: ENC[AES256_GCM,data:oi2ZB2NmhnGEdCor3bSKm8xTgYr89mEA+KRtwWZWF0vw/xNZZXbWo0wK6yjTTXkkwkhGZ9CPiBrGELMoNc+u77iE0E6LnETXwe9OX3G0xQOHb4IB9UTXFnOIDSUgUMMynTGX8tur4Q9UX1OiQwGQErba+53tNw330I8H5whRUNg=,iv:RxRcqoJqG7cNuGlHRX71X9rVI4crCDazPjp+45vuA4M=,tag:usEU9qQYfXUTZdg9jJuhPQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
