apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:FAqYdaN6BKY=,iv:283IIM47BXOhUyGvmh3Wokw+F4OoghOrRqPPkYKpQxw=,tag:7Y/U/2/W4vVvShkA2F3FOA==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:g0IexuiKlrWdF3TQga7tkI2Zp8+XVA85pk2CqLsQIgZn6hpb,iv:rDqCkrFdsL5PG44Ntu6MkHyYYwTHwPzWLJhjhMqmiLA=,tag:6CoBa6xQEHlj+EUelef5Bg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFL2libkhXZ1dFQVB1TmJI
        ZCtwN2tqc0ZnN05tTVB4U1pOeFpUeFFUL1NVClpSdkVjRFdheEpvNzVaTU9DQS9Q
        Ni9NSkpzT0xRZ0RkeUo3VU15NjJxUTgKLS0tIGZsRnNWalFIMlBEUXdwM1R3Z2V4
        WTV1dm1Ydm9pZHdhUXJCemU2TjViYm8KblyOxbdqA7rN5UatrZSbfr6hduMBtdDW
        8LE22tOQc9jWk8E6OmE3lFEieyalBUuV87lk0VLvdsEuF7MPEEAZ1w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ryhy9dduzk5hyn33lnm7swtg72r7luklfv397s3wmhqav099w95s3cu3rh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-14T16:22:20Z"
  mac: ENC[AES256_GCM,data:l9iFtZefg2GEa9zqnWANHbXI/4xaGv07SFIvyYPGzxRpD2ceGNs6xf3WbOAFsujwopxUmSnz/k2xJ8TXVNsMvSFVzSywbqMKTWbJ0v5uKHI2Ie7fl276ByMLUhO/X5mgGHHrLfc5OY3265fNXwjksEhYsFB3FakIuHUwaNWuGu0=,iv:OzWcI45+k5/y1bcMyBwm0YxdENkpXuJqiZhTO1RUc5A=,tag:UHjwfODpo2mzSc9lZD2bNA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
