---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: deluge
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/linuxserver/deluge
      tag: latest@sha256:3b1df281d71f016ea1d1c608ea35e3be19bb641cd349025eec5c2a7580fca8c2
    env:
      TZ: "${TIMEZONE}"
      PUID: "1000"
      PGID: "1000"
      DELUGE_LOGLEVEL: "info"
    service:
      main:
        ports:
          http:
            port: 8112

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: "simple-icons:d"
          hajimari.io/group: "downloader"
        hosts:
          - host: &host "torrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: deluge-config
      nfs-nas-media:
        enabled: true
        existingClaim: media-nfs-share-pvc
        mountPath: /media
        readOnly: false
    # hostname: torrent

    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 6000Mi

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: nvidia.com/gpu
                  operator: In
                  values:
                    - "false"
