name: Block Merge on "hold" Tag

on:
  pull_request:
    types:
      - synchronize
      - labeled
      - unlabeled

jobs:
  block_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - name: Check PR for "hold" tag
        id: check_tag
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          if [[ $(git diff --name-only HEAD^ HEAD) =~ .github/workflows/block_merge.yml ]]; then
            echo "has_hold_tag=false" >> $GITHUB_ENV
          else
            pr_labels=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq ".labels[].name")
            has_hold=false
            for label in $pr_labels; do
              if [[ "${label,,}" == "do not merge" ]]; then
                has_hold=true
                break
              fi
            done <<< "$pr_labels"
            echo "has_hold_tag=$has_hold" >> $GITHUB_ENV
          fi

      - name: Block Merge
        if: env.has_hold_tag == 'true'
        run: |
          echo "This pull request has a 'hold' tag. Merging is blocked."
          exit 1
