name: Block Merge on "hold" Tag

on:
  pull_request:
    types:
      - synchronize
      - labeled
      - unlabeled

jobs:
  block_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0

      - name: Check PR for "hold" tag
        id: check_tag
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          if [[ $(git diff --name-only HEAD^ HEAD) =~ .github/workflows/block_merge.yml ]]; then
            echo "has_hold_tag=false" >> $GITHUB_ENV
          else
            pr_tags=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name')
            if [[ $pr_tags =~ hold ]]; then
              echo "has_hold_tag=true" >> $GITHUB_ENV
            else
              echo "has_hold_tag=false" >> $GITHUB_ENV
            fi
          fi

      - name: Block Merge
        if: env.has_hold_tag == 'true'
        run: |
          echo "This pull request has a 'hold' tag. Merging is blocked."
          exit 1
