---
name: PR Check

on:
  pull_request:
    branches: ["main"]

jobs:
  scan:
    name: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
      - uses: harupy/find-trailing-whitespace@56310d70ae8fd21afec8d4307d2d9ab6c15e7c5d # master
      - name: "Gitleaks checks"
        uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e # v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Copy changed files"
        run: |
          mkdir testfiles
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "$file" == .github/* ]]; then
              continue
            fi
            if [ -f "$file" ]; then
              cp --parents "$file" testfiles
            fi
          done
      - name: "Yamllint checks"
        uses: karancode/yamllint-github-action@4052d365f09b8d34eb552c363d1141fd60e2aeb2 # master
        with:
          yamllint_config_filepath: .github/linters/.yamllint.yaml
          yamllint_file_or_dir: "testfiles"
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
