---
name: Scan Containers

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths:
      - "kubernetes/**/*.yaml"
      - "kubernetes/**/*.yml"

permissions:
  contents: read

jobs:
  detect-file-changes:
    name: Detect File Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: filter
        with:
          list-files: json
          filters: |
            yaml:
              - added|modified: "kubernetes/**/*.yaml"
              - added|modified: "kubernetes/**/*.yml"
    outputs:
      yaml_files: ${{ steps.filter.outputs.yaml_files }}
  detect-containers:
    name: Detect Containers
    runs-on: ubuntu-latest
    needs: detect-file-changes
    strategy:
      matrix:
        file: ${{ fromJSON(needs.detect-file-changes.outputs.yaml_files) }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install Jo
        run: |
          sudo apt-get update && sudo apt-get install -y jo
      - name: Detect Containers in Files
        id: containers
        run: |
          containers=$(.github/scripts/container-parser.sh --file "${{ matrix.file }}")
          echo "${containers}"
          echo "containers=${containers}" >> $GITHUB_OUTPUT
    outputs:
      containers: ${{ steps.containers.outputs.containers }}
  scan-containers:
    name: Scan Containers
    runs-on: ubuntu-latest
    needs: detect-containers
    permissions:
      security-events: write
    strategy:
      matrix: ${{ fromJSON(needs.detect-containers.outputs.containers) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Cache Trivy DB
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .trivy-cache
          key: trivy-db-${{ github.run_id }}
          restore-keys: trivy-db-
      - name: Scan Container
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: ${{ matrix.containers }}
          vuln-type: os,library
          severity: CRITICAL,HIGH
          format: sarif
          output: trivy-results.sarif
          cache-dir: .trivy-cache
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@9e0d7b8d25671d64c341c19c0152d693099fb5ba # v4
        with:
          sarif_file: trivy-results.sarif
