---
name: Scan Containers

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths:
      - "kubernetes/**/*.yaml"
      - "kubernetes/**/*.yml"

permissions:
  contents: read

jobs:
  detect-file-changes:
    name: Detect File Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4
        id: filter
        with:
          list-files: json
          filters: |
            yaml:
              - added|modified: "kubernetes/**/*.yaml"
              - added|modified: "kubernetes/**/*.yml"
    outputs:
      yaml_files: ${{ steps.filter.outputs.yaml_files }}
  detect-containers:
    name: Detect Containers
    runs-on: ubuntu-latest
    needs: detect-file-changes
    strategy:
      matrix:
        file: ${{ fromJSON(needs.detect-file-changes.outputs.yaml_files) }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Install Jo
        run: |
          sudo apt-get update && sudo apt-get install -y jo
      - name: Detect Containers in Files
        id: containers
        run: |
          containers=$(.github/scripts/container-parser.sh --file "${{ matrix.file }}")
          echo "${containers}"
          echo "containers=${containers}" >> $GITHUB_OUTPUT
    outputs:
      containers: ${{ steps.containers.outputs.containers }}
  scan-containers:
    name: Scan Containers
    runs-on: ubuntu-latest
    needs: detect-containers
    permissions:
      security-events: write
    strategy:
      matrix: ${{ fromJSON(needs.detect-containers.outputs.containers) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Cache Trivy DB
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: .trivy-cache
          key: trivy-db-${{ github.run_id }}
          restore-keys: trivy-db-
      - name: Scan Container
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: ${{ matrix.containers }}
          vuln-type: os,library
          severity: CRITICAL,HIGH
          format: sarif
          output: trivy-results.sarif
          cache-dir: .trivy-cache
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@e4fba868fa4b1b91e1fdab776edc8cfbe6e9fb81 # v4
        with:
          sarif_file: trivy-results.sarif
