---
name: Yayamlls

on:
  pull_request:
    branches: ["main"]
    paths: ["kubernetes/**"]

jobs:
  validate:
    name: Yayamlls - Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Install yayamlls
        run: go install github.com/home-operations/yayamlls/cmd/yayamlls@0.1.11

      - name: Validate manifests
        run: |
          export PATH="$(go env GOPATH)/bin:$PATH"
          yayamlls validate kubernetes/
