---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: microbin
spec:
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      version: 3.4.0
  values:
    controllers:
      microbin:
        containers:
          app:
            env:
              MICROBIN_PUBLIC_PATH: "https://pastebin.${SECRET_DOMAIN}"
              MICROBIN_PORT: "80"
              MICROBIN_DATA_DIR: &data /var/lib/microbin
            envFrom:
              - secretRef:
                  name: microbin-secret
            image:
              repository: ghcr.io/vaskozl/microbin-bin
              tag: 2.0.4@sha256:0c988cbbcbbd029715f2985d0a87f93e58bc4678424f54ff7fbd6c31b24c9a38
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              limits:
                memory: 80Mi
              requests:
                cpu: 10m
                memory: 10Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
        statefulset:
          podManagementPolicy: Parallel
          volumeClaimTemplates:
            - name: data
              accessMode: ReadWriteOnce
              storageClass: longhorn-media
              size: 200Mi
              globalMounts:
                - path: *data
        type: statefulset
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
    ingress:
      app:
        className: external
        annotations:
          gatus.io/enabled: "true"
          hajimari.io/icon: simple-icons:pastebin
        hosts:
          - host: &host "pastebin.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    service:
      app:
        controller: microbin
        ports:
          http:
            port: 80
