---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: midarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-init:17.4
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: midarr-secret
    controller:
      replicas: 1
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/midarrlabs/midarr-server
      tag: v4.2.0@sha256:b368f94a8a7e0657125da108129ffbdc92d04fc7fba302ea88d9396b125b4d03
    env:
      TZ: ${TIMEZONE}
      APP_URL: http://midarr.media.svc.cluster.local:4000
      RADARR_BASE_URL: radarr.media.svc.cluster.local
      SONARR_BASE_URL: sonarr.media.svc.cluster.local
    envFrom:
      - secretRef:
          name: midarr-secret
    service:
      main:
        ports:
          http:
            port: 4000
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:play-circle-outline
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      nfs-nas-media:
        enabled: true
        existingClaim: media-nfs-share-pvc
        mountPath: /media
        readOnly: true
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 1000Mi
